logging:
  format: json

services:
  gologger:
    url: http://gologger:3001/

decision_logs:
  # console: true
  service: gologger
  path: /
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10