# docker-compose.yml
services:
  opa:
    image: openpolicyagent/opa:1.0.0
    command: run --server --addr :8181 --bundle /bundle/bundle.tar.gz -c /config/config.yml
    ports:
      - "8181:8181"
    volumes:
      - ./config/:/config
      - ./package:/bundle

    networks:
      - opa-network
    depends_on:
      gologger:
        condition: service_healthy

  gologger:
    build:
      context: ./gologger
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - opa-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3001"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

networks:
  opa-network:
    driver: bridge