services:
  gologger:
    build: ./gologger
    image: gologger
    ports:
      - 3001:3001
  opa:
    image: openpolicyagent/opa:0.70.0
    ports:
      - 8181:8181
    volumes:
      - .:/config
    command: ["run", "--server", "-c", "/config/config.yml", "/config/policy.rego", "/config/mask.rego"]

networks:
  opa-network:
    driver: bridge