logging:
  format: json
  level: debug

services:
  gologger:
    url: http://gologger:3001

decision_logs:
  service: gologger
  path: /logs
  reporting:
    min_delay_seconds: 5
    max_delay_seconds: 10
    upload_timeout_seconds: 15